DROP TABLE IF EXISTS HCA.DISEASE;

CREATE TABLE HCA.DISEASE(
CASE_ID VARCHAR(100) NOT NULL,
DB_ID VARCHAR(10) NOT NULL,
DISEASE_ID SMALLINT NOT NULL,
DISEASE_LABEL VARCHAR(500) NOT NULL
);

CREATE INDEX DISEASE_IDX ON HCA.DISEASE(CASE_ID);
