DROP TABLE IF EXISTS HCA.PUBLICATION;

CREATE TABLE HCA.PUBLICATION(
CASE_ID VARCHAR(100) NOT NULL,
TITLE VARCHAR(50) NOT NULL,
AUTHORS VARCHAR(300) NOT NULL,
PMID VARCHAR(10) NOT NULL
);

CREATE INDEX PUBLICATION_IDX ON HCA.PUBLICATION(CASE_ID);
