DROP TABLE IF EXISTS HCA.VARIANT;

CREATE TABLE HCA.VARIANT(
CASE_ID VARCHAR(100) NOT NULL,
VARIANT_ID VARCHAR(200) NOT NULL,
ASSEMBLY VARCHAR(10) NOT NULL, -- genome assembly, e.g. GRCh37, GRCh38
CONTIG VARCHAR(25) NOT NULL,
POS INT NOT NULL, -- 1-based start coordinate of the variant on FWD strand
POS2 INT NOT NULL, -- 1-based end coordinate of the variant on FWD strand
REF_ALLELE VARCHAR(100) NOT NULL,
ALT_ALLELE VARCHAR(100) NOT NULL,
GENOTYPE VARCHAR(20) NOT NULL,
VARIANT_CLASS VARCHAR(30) NOT NULL,
PATHOMECHANISM VARCHAR(200),
CONSEQUENCE VARCHAR(200)
);

CREATE INDEX VARIANT_IDX ON HCA.VARIANT(CASE_ID);
