DROP TABLE IF EXISTS HCA.PHENOTYPE;

CREATE TABLE HCA.PHENOTYPE(
CASE_ID VARCHAR(100) NOT NULL,
DB_ID VARCHAR(10) NOT NULL,
DISEASE_ID SMALLINT NOT NULL,
DISEASE_LABEL VARCHAR(500) NOT NULL
);

CREATE INDEX PHENOTYPE_IDX ON HCA.PHENOTYPE(CASE_ID);
