DROP TABLE IF EXISTS HCA.FAMILY_INFO;

CREATE TABLE HCA.FAMILY_INFO(
CASE_ID VARCHAR(100) NOT NULL,
FAMILY_ID VARCHAR(100) NOT NULL,
SEX VARCHAR(20) NOT NULL,
AGE VARCHAR(100) NOT NULL
);

CREATE INDEX FAMILY_INFO_IDX ON HCA.FAMILY_INFO(CASE_ID);
