# This is the template file which contains lists of choices used to populate
# content of HRMD gui.
#
# Feel free to add, modify or remove list elements. Everything will work as
# long as you'll adhere to Yaml syntax and prevent changing list names.
# (List -> chromosome, genotype, pathomechanism... ). That would
# certainly break the program and make you hit the roof.

## Shared among all modes ##############################################
# Deprecated in favor of protobuf GenomeAssembly enum
#genomeBuild: ['hg19', 'hg38']

# Chromosomes. Self-explanatory, huh?
chromosome: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']

# Variant class - the root term of pathomechanism.
variantClass: ['coding', 'enhancer', 'promoter', 'splicing', 'structural', '5UTR',
  '3UTR', 'ICR', 'microRNAgene', 'RNP_RNAcomponent', 'LINC_RNA',
  'unknown']

# Pathomechanism
pathomechanism: ['unknown', 'coding|missense', 'coding|stop-codon', 'coding|frameshift',
  'coding|unknown', 'enhancer|unknown',
  'enhancer|reduced-transcription','enhancer|inappropriate-transcription',
  'enhancer|increased-transcription','enhancer|protein-binding','enhancer|protein-binding|disrupted',
  'enhancer|protein-binding|novel','enhancer|intronic','promoter|unknown',
  'promoter|reduced-transcription','promoter|increased-transcription',
  'splicing|unknown',
  'splicing|5ss|disrupted',
  'splicing|3ss|disrupted',
  'splicing|branchpoint|disrupted',
  'splicing|5css|activated',
  'splicing|3css|activated',
  'splicing|SRE',
  'splicing|SRE|ESS',
  'splicing|SRE|ESE',
  'splicing|SRE|ESE|binding|decreased',
  'splicing|SRE|ESE|binding|increased',
  'splicing|SRE|ESS|binding|decreased',
  'splicing|SRE|ESS|binding|increased',
  'splicing|SRE|ISE',
  'splicing|SRE|ISS',
  '5UTR|unknown',
  '5UTR|transcription','5UTR|reduced-transcription','5UTR|increased-transcription',
  '5UTR|uORF','5UTR|uORF|reduced-translation','5UTR|uORF|increased-translation',
  '5UTR|uORF|increased-translation|uORF-disruption','5UTR|uORF|reduced-translation|novel-uORF',
  '5UTR|secondary-structure','5UTR|secondary-structure|base-pairing',
  '5UTR|secondary-structure|base-pairing|disrupted','5UTR|secondary-structure|base-pairing|novel',
  '5UTR|start-codon','5UTR|start-codon|disrupted','5UTR|kozak','5UTR|kozak|disrupted','5UTR|IRE',
  '5UTR|IRE|disrupted',
  '5UTR|constitutional-epimutation',
  '5UTR|splice-defect',
  '3UTR|unknown',
  '3UTR|increased-expression',
  '3UTR|reduced-expression',
  '3UTR|microRNA-binding-site','3UTR|microRNA-binding-site|disrupted','3UTR|microRNA-binding-site|created',
  '3UTR|polyadenylation-signal','3UTR|polyadenylation-signal|disrupted','3UTR|secondary-structure',
  '3UTR|secondary-structure|base-pairing','3UTR|secondary-structure|base-pairing|disrupted',
  '3UTR|protein-binding|disrupted',
  'imprinting-control-region','microRNA-gene','RNA-gene','RNA-gene|base-pairing',
  'RNA-gene|base-pairing|disrupted']

# Impact on sequence, mainly splicing-related impacts. Inspired by Gene XII - page 521
consequence: ["Exon skipping", "Intron retention",
  "Alternative/cryptic 5' splice site", "Alternative/cryptic 3' splice site",
  "Alternative 5' and 3' splice sites", "Pseudoexon inclusion",
  "Splicing of mutually exclusive exon", # Due to a mutation exon B is spliced in INSTEAD of exon A
  "Multiple exons skipped", "Alternative promoter/splicing",
  "Alternative polyadenylation/splicing",
  "Increased inclusion of alternatively spliced exon",
  "epigenetic silencing",
  "Is there any other consequence?", "Not investigated", "None"]

# Set the database (please use the OMIM id if at all possible). For
# OMIM, use the phenotype id, and not the gene id!.
diseaseDatabases: ['OMIM', 'NCI']

# Comparability -> This is the weakest evidence class. Enter yes if the
# reason for believing that the mutation is pathogenic is simply that it
# is comparable to other published mutations of comparable type in the
# gene.
comparability: ['yes', 'no']

# Cosegregation -> enter yes if the mutation cosegregates with the
# disease in the family being investigated.
cosegregation: ['yes', 'no']

### Specific for Splicing mutations ####################################

# Source of material used for validation - To be removed
#materialSource: ['Patient', 'in-vitro']

# Assay type - To be removed
#assayType: ['Minigene', 'Site directed mutagenesis', 'Real-time PCR', 'RNA (cDNA) sequencing', 'CRISPR-Cas',
#  'SR-protein overexpression', 'SR-protein-knockdown', 'PCR']

# Name of the agent used in experiment - To be removed
#agentName: ['dsx', 'RTB', 'pCG', 'pCR4.1-TOPO', 'pET01', 'pSL1180',
#  'pSPL', 'pSXN', 'hnRNPA1', 'SRSF1|SF2/ASF', 'SRSF2|SC35', 'SRSF3|SRp20', 'SRSF4|SRp75', 'SRSF5|SRp40', 'SRSF6|SRp55',
#  'SRSF7|9G8', 'SRSF8|SRp46', 'SRSF9|SRp30c', 'SRSF10|SRp38', 'SRSF11|p54', 'SRSF12|SRrp35']

# Quantification method - To be removed
#quantificationMethod: ['Semi-quantitative PCR', 'Fluorescence-based quantification', 'RT-PCR',
#  'Approximation']

# Tissue type or cell line used - To be removed
#tissueOrCellLine: ['skeletal muscle', 'fibroblasts', '293T', 'COS-7', 'HEK293', 'HeLa', 'CHO', 'GH3']


### Specific for Mendelian mutations ###################################
# Luciferase assay (or the similar CAT assay) to judge transcriptional
# activity. Indicate whether the mutation is associated with increased
# activity (up) or decreased activity (down) as compared with the
# wildtype construct (in percent).
reporter: ['no', 'up', 'down']

# EMSA (electrophoretic mobility shift assay). This is used to indicate
# whether a protein binds to a given DNA sequence. For our purposes, we
# are referring to the protein affected by the mutation. Enter the
# corresponding protein if there is a change in binding. Enter the
# Entrez Gene ID and Gene Symbol of the protein that is affected by the
# mutation (usually a transcription factor)
emsa: ['yes', 'no']

# Other "choices"
otherChoices: ['no', 'up', 'down', 'demonstrated']

# This is for any other kind of experimental assay that shows an effect
# of a regulatory or non-coding mutation. The categories are at present:
otherEffect: ['Telomerase', 'Nonspecific_EMSA', 'Coding', 'ChIP assay',
  'Allele-specific Q-PCR', 'miRNA-activity assay', 'in vitro mRNA expression assay', 'Transgenic model',
  'level of recombinant mutant protein', 'Exon skipping', 'Intron retention', 'Cryptic splice site', 'Ask Peter']

# For now this is hardcoded into checkboxes in SplicingVariantController/View
# spliceValidation: ['Minigene', 'Site-directed mutagenesis', 'Real-time PCR (patient sample)', 'cDNA sequencing (patient sample)',
# 'SR protein knockdown','SR protein overexpression', 'Mutation of WT splice site', 'Other']


## eof ##
